import {randomUUID} from 'node:crypto';
import {authorize,readBody,validateOrigin} from '../../../lib/auth';
import {act,state} from '../../../lib/engine';
export const runtime='nodejs';export const dynamic='force-dynamic';
const tools=[{name:'veyro_policy',description:'Read the current Veyro spending policy and attempt history. Testnet or rehearsal only.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},{name:'veyro_research',description:'Search crypto X for classic Solana token mint candidates. Paid read-only X API calls are capped and cached. Fixtures are available when liveResearch is false.',inputSchema:{type:'object',properties:{intent:{type:'string'},budget:{type:'string'},liveResearch:{type:'boolean'}},required:['intent','budget'],additionalProperties:false},annotations:{readOnlyHint:false,openWorldHint:true}},{name:'veyro_execute',description:'Research then purchase a valueless TEST-MEME proxy token using a pre-existing owner policy. This never purchases the mainnet research candidate and never enables mainnet. Requires a unique requestId to avoid duplicate execution. Cannot change owner limits or revoke.',inputSchema:{type:'object',properties:{requestId:{type:'string'},intent:{type:'string'},budget:{type:'string'},liveResearch:{type:'boolean'}},required:['requestId','intent','budget'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true}}];
export async function POST(req:Request){let id:unknown=null;try{validateOrigin(req);const auth=authorize(req);const msg=await readBody(req);id=msg.id??null;if(msg.method==='notifications/initialized')return new Response(null,{status:202});let result:unknown;
 if(msg.method==='initialize')result={protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'veyro-live',version:'0.1.0'}};
 else if(msg.method==='tools/list')result={tools};
 else if(msg.method==='tools/call'){const name=msg.params?.name;const args=msg.params?.arguments||{};let value;if(name==='veyro_policy')value=await state(auth.session);else if(name==='veyro_research'||name==='veyro_execute'){value=await act(auth.session,{intent:args.intent,budget:args.budget,liveResearch:args.liveResearch===true,action:name==='veyro_research'?'research':'run',requestId:name==='veyro_research'?randomUUID():args.requestId},false);}else throw Error('UNKNOWN_TOOL');result={content:[{type:'text',text:JSON.stringify(value)}]};}
 else throw Error('METHOD_NOT_FOUND');return Response.json({jsonrpc:'2.0',id,result});
 }catch(e){return Response.json({jsonrpc:'2.0',id,error:{code:-32000,message:(e as Error).message}},{status:(e as Error).message==='UNAUTHORIZED'?401:400});}}
export async function GET(){return new Response('This endpoint supports JSON POST requests.',{status:405,headers:{Allow:'POST'}});}
