'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Policy={active:boolean;maxAmount:string;totalLimit:string;spent:string;expiresAt:number;address:string;agent:string};
type Attempt={id:string;at:string;kind:string;decision:string|null;reason:string;status:string;executedSignature?:string;candidateSignature?:string;selected?:{name:string;symbol:string;mint:string|null};research?:{source:string;candidates:{name:string;symbol:string;mint:string|null;score:number;sourceUrl:string|null;reason:string}[]};request?:{intent?:{text:string}}};
type State={mode:string;network:string;xConfigured:boolean;configured:boolean;policy:Policy|null;attempts:Attempt[];error?:string};
const dollars=(n:string)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(BigInt(n||'0'))/1e6);
const short=(s:string)=>s.length>20?s.slice(0,6)+'…'+s.slice(-5):s;
const initial:State={mode:'rehearsal',network:'Connecting',xConfigured:false,configured:false,policy:null,attempts:[]};
export default function Live(){const [data,setData]=useState<State>(initial),[tab,setTab]=useState('Overview'),[intent,setIntent]=useState('Find the dumbest meme coin. Here’s $100. Make me money.'),[budget,setBudget]=useState('100'),[total,setTotal]=useState('150'),[hours,setHours]=useState('1'),[liveResearch,setLiveResearch]=useState(false),[scenario,setScenario]=useState('approved'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[token,setToken]=useState(''),[session,setSession]=useState(''),[showSettings,setShowSettings]=useState(false),[requestId,setRequestId]=useState(''),[dark,setDark]=useState(false);
useEffect(()=>{let id=localStorage.getItem('veyro-session');if(!id){id=crypto.randomUUID();localStorage.setItem('veyro-session',id);}setSession(id);setRequestId(crypto.randomUUID());},[]);
useEffect(()=>{if(session)void refresh();},[session]);
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
function headers(){return {'Content-Type':'application/json','x-veyro-session':session,...(token?{Authorization:'Bearer '+token}:{})};}
async function refresh(){try{const r=await fetch('/api/state',{headers:headers(),cache:'no-store'});const v=await r.json();setData(v);if(v.error)setMessage(v.error);}catch{setMessage('Could not reach Veyro. Check your connection and try Refresh.');}}
async function action(kind:string){if(busy)return;setBusy(true);setMessage('');try{const id=kind==='run'?requestId:crypto.randomUUID();const r=await fetch('/api/action',{method:'POST',headers:headers(),body:JSON.stringify({action:kind,requestId:id,intent,budget,total,hours,liveResearch,scenario})});const v=await r.json();if(v.error)throw Error(v.error);setData(v);setMessage(v.attempt?.reason||'Updated');if(kind==='run')setRequestId(crypto.randomUUID());}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
const p=data.policy,remaining=p?BigInt(p.totalLimit)-BigInt(p.spent):0n,latest=data.attempts.find(a=>a.kind==='run'||a.kind==='research');
return <><header className="topbar"><a className="logo" href="/" aria-label="Veyro home"><svg viewBox="0 0 28 28"><path d="M3 5h7l5 15 5-15h6L17 26h-6Z"/></svg><b>veyro</b></a><span className="slash">/</span><span className="team">Your workspace</span><span className="tag">Test deployment</span><div className="topright"><a href="https://github.com/veyro-real/veyro-protocol">Documentation ↗</a><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Toggle color theme">{dark?'☀':'◐'}</button><button className="avatar" onClick={()=>setShowSettings(!showSettings)} aria-label="Open access settings">V</button></div></header>
<nav className="tabs" aria-label="Workspace navigation">{['Overview','Policy','Activity','Connect'].map(t=><button key={t} onClick={()=>setTab(t)} aria-current={tab===t?'page':undefined} className={tab===t?'selected':''}>{t}</button>)}</nav>
<main><div className="titlebar"><div><h1>{tab==='Overview'?'Agent workspace':tab==='Policy'?'Spending policy':tab==='Activity'?'Activity log':'Connect your agent'}</h1><p>{tab==='Overview'?'Tell it what you want. Set the limits. Let it work.':tab==='Policy'?'You define the boundary. The protocol enforces it.':tab==='Activity'?'Every admitted attempt. Every decision. Every receipt.':'The same actions, directly from your chat client.'}</p></div><div className="title-actions"><span className="network"><i/>{data.network}</span><button className="secondary" onClick={refresh} disabled={busy}>↻ Refresh</button></div></div>
<div className="notice"><span>ⓘ</span><p>{data.mode==='testnet'?'Solana testnet · TEST-USD and TEST-MEME have no monetary value. Live X candidates are mainnet assets; this demo buys a separate proxy token.':'Rehearsal mode · Explore the full workflow without a wallet. Purchases and balances are simulated; no blockchain transactions are sent.'}</p><button onClick={()=>setShowSettings(!showSettings)}>Connection settings ↗</button></div>
{showSettings&&<section className="settings panel"><div><h2>Testnet operator access</h2><p>Use the operator access token configured on your server. It stays in this tab’s memory.</p></div><label>Access token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="Operator token"/></label><button className="primary" onClick={async()=>{await refresh();setShowSettings(false);}}>Connect</button><p className="fine">X credentials and wallet keys belong on the server. Never paste a wallet seed here.</p></section>}
{message&&<div className="feedback" role="status"><span>{message.replaceAll('_',' ')}</span><button aria-label="Dismiss status" onClick={()=>setMessage('')}>×</button></div>}
{(tab==='Overview'||tab==='Policy')&&<div className="metrics"><div><span>Available budget</span><strong>{p?dollars(remaining.toString()):'—'}<small> TEST-USD</small></strong><p>Lifetime allocation remaining</p></div><div><span>Per-purchase limit</span><strong>{p?dollars(p.maxAmount):'—'}<small> TEST-USD</small></strong><p>Checked before execution</p></div><div><span>Agent permission</span><strong className="permission"><i className={p?.active?'ok-dot':'off-dot'}/>{p?(p.active?'Active':'Revoked'):'Not connected'}</strong><p>{p?'Expires '+new Date(p.expiresAt*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Configure testnet to begin'}</p></div></div>}
{tab==='Overview'&&<div className="workspace-grid"><section className="panel composer"><div className="panel-heading"><h2>What’s the move?</h2><span className="tag">Agent run</span></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();void action('run');}}><label htmlFor="intent" className="sr-only">Your agent instruction</label><textarea id="intent" value={intent} onChange={e=>setIntent(e.target.value)} maxLength={2000}/><div className="compose-controls"><label>Spend up to<div className="amount-input"><span>$</span><input aria-label="Purchase budget" inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)}/><span>TEST-USD</span></div></label><button className="primary" disabled={busy||!p} type="submit">{busy?'Working…':'Run agent'} <span>↑</span></button></div><div className="research-toggle"><label><input type="checkbox" checked={liveResearch} disabled={!data.xConfigured} onChange={e=>setLiveResearch(e.target.checked)}/> Search crypto X</label><span>{data.xConfigured?'Read-only · capped requests':'Fixtures enabled · X not connected'}</span></div></form><div className="divider"/><div className="scenario"><label htmlFor="scenario">Test the boundary</label><select id="scenario" value={scenario} onChange={e=>setScenario(e.target.value)}><option value="approved">Approved purchase</option><option value="over-limit">Exceed purchase limit</option><option value="cumulative">Exceed lifetime budget</option><option value="unauthorized">Unapproved recipient</option><option value="compromised">Compromised-agent request</option></select><p>The attack scenarios use the same agent identity. The proposed action changes.</p></div></section>
<section className="panel flow"><div className="panel-heading"><h2>Execution pipeline</h2><span className="subtle">01 → 04</span></div><ol>{[['Intent','Goal and a separate numeric budget.'],['Research',latest?.research?latest.research.source:'X search or labeled fixtures.'],['Authorization',latest?.decision?latest.decision+' · '+latest.reason.replaceAll('_',' '):'Current policy, before execution.'],['Settlement',latest?.status==='FINALIZED'?'Finalized on Solana':latest?.status==='REHEARSED'?'Rehearsal only. No transaction sent.':'Awaiting an authorized purchase.']].map(([t,s],i)=><li key={t}><span className="step-number">{latest&&i<2?'✓':i+1}</span><div><h3>{t}</h3><p>{s}</p></div>{i===2&&latest?.decision&&<span className={'verdict '+latest.decision.toLowerCase()}>{latest.decision}</span>}</li>)}</ol><div className="pipeline-footer"><span>▧ Solana authorization</span><a href="https://github.com/veyro-real/veyro-protocol">View source ↗</a></div></section></div>}
{tab==='Overview'&&<section className="panel research"><div className="panel-heading"><h2>Research candidates</h2><span className="tag">{latest?.research?.source||'No research yet'}</span></div>{latest?.research?<div className="candidates">{latest.research.candidates.map((c,i)=><article key={c.mint||c.symbol}><div className="coin-icon">{c.symbol.slice(0,1)}</div><div><h3>{c.name} {i===0&&<span className="tiny-tag">Candidate</span>}</h3><p>{c.reason}</p>{c.mint&&<code>{short(c.mint)}</code>}</div><div className="candidate-score"><strong>{c.score}</strong><span>engagement score</span>{c.sourceUrl&&<a href={c.sourceUrl} target="_blank" rel="noreferrer">View post ↗</a>}</div></article>)}</div>:<div className="empty"><span>⌕</span><h3>Your agent’s research will appear here.</h3><p>Run an intent to see candidates and their source.</p></div>}</section>}
{tab==='Policy'&&<div className="workspace-grid"><section className="panel policy-form"><div className="panel-heading"><h2>Owner-defined limits</h2><span className="tag">Owner action</span></div><label>Maximum per purchase · TEST-USD<input value={budget} onChange={e=>setBudget(e.target.value)} inputMode="decimal"/></label><label>Lifetime spending limit · TEST-USD<input value={total} onChange={e=>setTotal(e.target.value)} inputMode="decimal"/></label><label>Expires after · hours<input value={hours} onChange={e=>setHours(e.target.value)} type="number" min="0.05" max="24" step="0.05"/></label><button className="primary" disabled={busy} onClick={()=>action('configure')}>Create policy</button><p className="fine">On testnet, revoke the existing policy before creating a replacement. Previous spending is never reset.</p></section><section className="panel policy-details"><div className="panel-heading"><h2>Authorization scope</h2></div><dl><dt>Network</dt><dd>{data.network}</dd><dt>Allowed asset</dt><dd>TEST-USD → TEST-MEME</dd><dt>Route</dt><dd>Fixed-price test pool</dd><dt>Program</dt><dd>Classic SPL Token</dd><dt>Recipient</dt><dd>Configured test owner</dd><dt>Minimum output</dt><dd>990 units per input unit</dd><dt>Policy</dt><dd><code>{p?short(p.address):'Not connected'}</code></dd></dl><button className="danger" disabled={busy||!p?.active} onClick={()=>action('revoke')}>Revoke agent access</button><p className="fine">Effective in chain order. A transaction settled before revocation cannot be undone.</p><button className="secondary" disabled={busy||data.mode!=='testnet'} onClick={()=>action('faucet')}>Request test SOL for execution fees ↗</button></section></div>}
{(tab==='Activity'||tab==='Overview')&&<section className="panel activity"><div className="panel-heading"><h2>Recent activity <span className="count">{data.attempts.length}</span></h2><button className="text-button" disabled={busy} onClick={()=>action('reconcile')}>Reconcile receipts ↻</button></div>{data.attempts.length?<div className="table-scroll"><table><thead><tr><th>Action</th><th>Decision</th><th>Outcome</th><th>When</th><th>Receipt</th></tr></thead><tbody>{data.attempts.slice(0,tab==='Overview'?5:100).map(a=><tr key={a.id}><td><strong>{a.kind==='run'?'Agent purchase':a.kind}</strong><span className="reason">{a.reason.replaceAll('_',' ')}</span></td><td><span className={'verdict '+(a.decision||'').toLowerCase()}>{a.decision||'—'}</span></td><td>{a.status.toLowerCase()}</td><td>{new Date(a.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td>{a.executedSignature?<a href={'https://explorer.solana.com/tx/'+a.executedSignature+'?cluster=testnet'} target="_blank" rel="noreferrer">View ↗</a>:<span className="subtle">{a.candidateSignature?'Pending':'No transaction'}</span>}</td></tr>)}</tbody></table></div>:<div className="empty compact"><p>No attempts yet. Your first run starts the audit trail.</p></div>}</section>}
{tab==='Connect'&&<section className="panel connect"><span className="tag">MCP + HTTP</span><h2>Your chat. Your agent. Veyro underneath.</h2><p>Connect a bearer-token-capable MCP client to your deployed server. The agent can research, read policy and request an authorized test-token purchase. Owner controls stay separate.</p><div className="endpoint"><code>/api/mcp</code><button className="secondary" onClick={()=>{void navigator.clipboard.writeText(location.origin+'/api/mcp').then(()=>setMessage('Endpoint copied')).catch(()=>setMessage('Copy the /api/mcp endpoint from this page.'));}}>Copy URL</button></div><div className="tool-list"><div><code>veyro_policy</code><p>Inspect current permissions.</p></div><div><code>veyro_research</code><p>Find verified Solana mint candidates.</p></div><div><code>veyro_execute</code><p>Request a testnet proxy-token purchase.</p></div></div><p className="fine">Set VEYRO_AGENT_TOKEN on the server and send it as a Bearer token. The operator token must remain separate. Hosted OAuth discovery and native mobile-wallet custody are not implemented.</p><a className="secondary inline" href="https://github.com/veyro-real/veyro-live">Connection guide ↗</a></section>}
<footer><span><i/> {data.mode==='rehearsal'?'Rehearsal · no real funds':'Solana testnet · no real funds'}</span><span>Veyro / Early developer preview</span><a href="https://github.com/veyro-real">GitHub ↗</a></footer></main></>}
